### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by StudyCrw** [Camaltra/this-is-not-real-aerial-imagery#25]
Hello, when running your code,there is an problem that is TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' and the wrong file is:\src\ai\diffusion_process.py. How to solve it?

**Comment by Camaltra** [comment]
Hi StudyCrw!

Can you be more specific on what you did, what you ran as script, to get this error so that I could try to reproduce it and fix it?
If possible, copy paste the entire error with the line that cause the RunTime

Best regards,
Camaltra

**Comment by StudyCrw** [comment]
hi,Camaltra!

Glad to receive your reply! After downloading the source code from github, I opened your code as a project and set up the runtime environment. Because the from ai.mapping import MODEL_NAME_MAPPING method could not find the path, I changed it to from mapping import MODEL_NAME_MAPPING, and other contents remained unchanged. Then, when I try to execute your code, I get the error shown in the figure.

Best regards,
StudyCrw
![my_error](https://github.com/Camaltra/this-is-not-real-aerial-imagery/assets/141615683/dd6b3db2-b21f-42b1-9cae-a1547a0801b8)

**Comment by Camaltra** [comment]
Hi StudyCrw,

The error is related to typing. Typing is not mandatory for python as type are dynamics, but it improve a lot the readability. Which python version do you use? I bet you use a version older than 3.10 :D Cause the use of type like `dict`, `list` etc.. for typing hint was introduce in 3.9 and `|` was introduce in 3.10. In case you don't want for any reason upgrade your python version, you can change all the typing hint by they twin version from the package `typing`

```
from typing import Union, Dict, List

... 

schedule_fn_kwargs: Union[Dict, None]
```
And on the same time change the rest of the typing hint for all `|`, `dict` and `list` in the rest of the files. If I remember this is all I used for the project. After this, you shouldn't have any similar error.

Best,
Camaltra

**Comment by StudyCrw** [comment]
hi,Camaltra!

Glad to receive your reply! Thank you very much. The problem has been solved.

Best regards,
StudyCrw
